# Description: Configuration file for the ENZYMES_small dataset with combinatorial complexes using CCSD

is_cc: True

data: 
  data: ENZYMES_small_CC
  dir: './data'
  batch_size: 64
  test_split: 0.2
  max_node_num: 12
  max_feat_num: 10
  init: deg
  min_node_val: 1
  max_node_val: 1
  node_label: weight
  min_edge_val: 1
  max_edge_val: 1
  edge_label: weight
  d_min: 3
  d_max: 4
  lifting_procedure: cycles
  lifting_procedure_kwargs : {}

sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
  adj: 
    type: VE
    beta_min: 0.2
    beta_max: 1.0
    num_scales: 1000
  rank2:
    type: VE
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA_CC
  rank2: ScoreNetworkF
  conv: GCN
  num_heads: 4
  depth: 5
  adim: 28
  nhid: 28
  num_layers: 6
  num_linears: 2
  c_init: 2
  c_hid: 6
  c_final: 4
  use_bn: False
  cnum: 2  # only for cc and ScoreNetworkF
  num_layers_mlp: 1  # only for cc and ScoreNetworkF
  use_hodge_mask: True  # only for cc and ScoreNetworkF
  conv_hodge: HCN  # only for cc and ScoreNetworkA_CC
  nhid_h: 4 # only for cc and ScoreNetworkA_CC
  num_layers_h: 2  # only for cc and ScoreNetworkA_CC
  num_linears_h: 1  # only for cc and ScoreNetworkA_CC
  c_hid_h: 4  # only for cc and ScoreNetworkA_CC
  c_final_h: 2  # only for cc and ScoreNetworkA_CC
  adim_h: 4  # only for cc and ScoreNetworkA_CC
  num_heads_h: 2  # only for cc and ScoreNetworkA_CC
  
train:
  name: test
  num_epochs: 5000
  save_interval: 5000
  print_interval: 500
  reduce_mean: False
  lr: 0.01
  lr_schedule: True
  ema: 0.999
  weight_decay: 0.0001
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5

# Sampling after the training

sampler:
  predictor: S4
  corrector: None
  snr: 0.15
  scale_eps: 0.7
  n_steps: 1

sample:
  cc_nb_eval: 1000  # param only for cc datasets
  use_ema: True
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42
