# Description: Configuration file to sample from the QM9 dataset with combinatorial complexes used in our work CDSS

is_cc: True

data:
  data: QM9
  dir: './data'
  min_node_val: 6
  max_node_val: 9
  node_label: "symbol"
  min_edge_val: 1
  max_edge_val: 3
  edge_label: "bond_type"
  d_min: 3
  d_max: 9

ckpt: ccsd_qm9_CC

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.7
  n_steps: 1

sample:
  n_samples: 16  # param only for mol datasets
  cc_nb_eval: 1000  # param only for cc datasets
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42
